name: "Close stale issues"
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has become stale. Open a new issue if this problem still exist."
          stale-pr-message: "This PR has become stale. Please comment if you wish to pursue this PR."
          stale-issue-label: "issue-stale"
          exempt-issue-labels: "awaiting-approval,work-in-progress"
          stale-pr-label: "pr-stale"
          exempt-pr-labels: "awaiting-approval,work-in-progress"
          days-before-stale: 10
          days-before-close: 3
